"""Build the assets of a Coding Brain release.

    python scripts/build_release.py --out dist/release
    python scripts/build_release.py --out dist/old --version 0.8.99    # an older build, for update tests

Produces: coding_brain-<version>-py3-none-any.whl, constraints.txt (exact dependency versions,
generated by installing the wheel into a fresh virtual environment on the build platform),
release.json (version, state schema, upgrade compatibility, Python requirement, notes),
install.ps1, uninstall.ps1 and SHA256SUMS covering every other file.
"""
import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
import venv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MIN_UPGRADE_FROM = "0.9.0"  # first version with the local installer; older copies reinstall


def project_version(source: Path) -> str:
    return re.search(r'^version = "([^"]+)"', (source / "pyproject.toml").read_text(), re.M).group(1)


def notes_for(version: str) -> str:
    changelog = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
    match = re.search(rf"^## {re.escape(version)}\b.*?$(.*?)(?=^## |\Z)", changelog, re.M | re.S)
    return match.group(1).strip() if match else ""


def build(out: Path, version: str | None, constraints: Path | None) -> dict:
    out.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as scratch:
        source = Path(scratch) / "source"
        shutil.copytree(ROOT, source, ignore=shutil.ignore_patterns(
            ".git", "dist", "build", "*.egg-info", "__pycache__", ".venv", "gauntlet", "benchmarks", "tests"))
        if version:
            pyproject = source / "pyproject.toml"
            pyproject.write_text(re.sub(r'^version = "[^"]+"', f'version = "{version}"', pyproject.read_text(),
                                        count=1, flags=re.M))
        version = project_version(source)
        subprocess.run([sys.executable, "-m", "pip", "wheel", "--no-deps", "--disable-pip-version-check",
                        "-w", str(out), str(source)], check=True, capture_output=True)
    wheel = out / f"coding_brain-{version}-py3-none-any.whl"
    if not wheel.exists():
        raise SystemExit(f"Expected {wheel.name}")
    if constraints:
        shutil.copy2(constraints, out / "constraints.txt")
    else:
        with tempfile.TemporaryDirectory() as scratch:
            venv.create(scratch, with_pip=True)
            python = Path(scratch) / ("Scripts/python.exe" if sys.platform == "win32" else "bin/python")
            subprocess.run([str(python), "-m", "pip", "install", "--disable-pip-version-check", str(wheel)],
                           check=True, capture_output=True)
            frozen = subprocess.run([str(python), "-m", "pip", "freeze", "--exclude", "coding-brain"],
                                    check=True, capture_output=True, text=True).stdout
        (out / "constraints.txt").write_text(frozen, encoding="utf-8")
    sys.path.insert(0, str(ROOT))
    from brain.local.config import SCHEMA_VERSION
    requires = re.search(r'^requires-python = "([^"]+)"', (ROOT / "pyproject.toml").read_text(), re.M).group(1)
    prerelease = bool(re.search(r"(a|b|rc|dev)\d*$", version))
    info = {"version": version, "tag": f"v{version}", "state_schema": SCHEMA_VERSION,
            "min_upgrade_from": MIN_UPGRADE_FROM, "requires_python": requires,
            "channel": "dev" if prerelease else "stable", "notes": notes_for(version)}
    (out / "release.json").write_text(json.dumps(info, indent=2) + "\n", encoding="utf-8")
    shutil.copy2(ROOT / "installer" / "windows" / "install.ps1", out / "install.ps1")
    shutil.copy2(ROOT / "brain" / "local" / "assets" / "uninstall.ps1", out / "uninstall.ps1")
    lines = [f"{hashlib.sha256(path.read_bytes()).hexdigest()}  {path.name}"
             for path in sorted(out.iterdir()) if path.is_file() and path.name != "SHA256SUMS"]
    (out / "SHA256SUMS").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return info


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    parser.add_argument("--version", help="override the version (test builds only)")
    parser.add_argument("--constraints", help="use this constraints file instead of generating one")
    args = parser.parse_args()
    print(json.dumps(build(Path(args.out), args.version,
                           Path(args.constraints) if args.constraints else None), indent=2))


if __name__ == "__main__":
    main()
